In [1]:
import numpy as np

In [5]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [13]:
np.zeros((2,3,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [14]:
np.random.random((2,2))

array([[ 0.98800695,  0.99027884],
       [ 0.62090068,  0.97619943]])

In [15]:
np.full((2,2),7)

/home/lukasz/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 7.,  7.],
       [ 7.,  7.]])

In [16]:
np.arange(10,25,5)

array([10, 15, 20])

In [18]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [32]:
np.linspace(0,2,4)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ])

In [ ]:
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)

In [33]:
x, y, z = np.loadtxt('test.txt',
                    skiprows=1,
                    unpack=True)

In [43]:
x, y, z

(array([ 0.2536,  0.4839,  0.1292,  0.1781,  0.6253]),
 array([ 0.1008,  0.4536,  0.6875,  0.3049,  0.3486]),
 array([ 0.3857,  0.3561,  0.5929,  0.8928,  0.8791]))

In [41]:
my_array = np.loadtxt('test.txt',
                    skiprows=1,
                    unpack=True)

In [42]:
my_array

array([[ 0.2536,  0.4839,  0.1292,  0.1781,  0.6253],
       [ 0.1008,  0.4536,  0.6875,  0.3049,  0.3486],
       [ 0.3857,  0.3561,  0.5929,  0.8928,  0.8791]])

In [39]:
my_array2 = np.genfromtxt('test2.txt',
                      skip_header=1,
                      filling_values=-999)

In [40]:
my_array2

array([[  4.83900000e-01,   4.53600000e-01,   3.56100000e-01],
       [  1.29200000e-01,   6.87500000e-01,  -9.99000000e+02],
       [  1.78100000e-01,   3.04900000e-01,   8.92800000e-01],
       [ -9.99000000e+02,   5.80100000e-01,   2.03800000e-01],
       [  5.99300000e-01,   4.35700000e-01,   7.41000000e-01]])

In [48]:
x = np.arange(10,25,5)
np.savetxt('test4', x, delimiter=',')

In [49]:
x = np.ones((3,4))

In [50]:
x

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [51]:
y = np.random.random((3,4))

In [52]:
y

array([[ 0.05565729,  0.93806868,  0.08732231,  0.23835936],
       [ 0.68687569,  0.77811153,  0.01269301,  0.74608332],
       [ 0.06057524,  0.60345542,  0.19540861,  0.93850297]])

In [53]:
x + y

array([[ 1.05565729,  1.93806868,  1.08732231,  1.23835936],
       [ 1.68687569,  1.77811153,  1.01269301,  1.74608332],
       [ 1.06057524,  1.60345542,  1.19540861,  1.93850297]])

In [54]:
z = np.arange(4)

In [55]:
z

array([0, 1, 2, 3])

In [56]:
x - z

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [57]:
x = np.ones((3,4))

In [58]:
x

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [65]:
y = np.random.random((5,1,4))

In [66]:
y

array([[[ 0.26118599,  0.36307547,  0.04311228,  0.43436511]],

       [[ 0.26251822,  0.78173461,  0.3074989 ,  0.51768683]],

       [[ 0.3009548 ,  0.95142418,  0.6148881 ,  0.91253236]],

       [[ 0.54527207,  0.1591055 ,  0.52892601,  0.82171419]],

       [[ 0.70086359,  0.45821037,  0.50392236,  0.91462561]]])

In [67]:
x+y

array([[[ 1.26118599,  1.36307547,  1.04311228,  1.43436511],
        [ 1.26118599,  1.36307547,  1.04311228,  1.43436511],
        [ 1.26118599,  1.36307547,  1.04311228,  1.43436511]],

       [[ 1.26251822,  1.78173461,  1.3074989 ,  1.51768683],
        [ 1.26251822,  1.78173461,  1.3074989 ,  1.51768683],
        [ 1.26251822,  1.78173461,  1.3074989 ,  1.51768683]],

       [[ 1.3009548 ,  1.95142418,  1.6148881 ,  1.91253236],
        [ 1.3009548 ,  1.95142418,  1.6148881 ,  1.91253236],
        [ 1.3009548 ,  1.95142418,  1.6148881 ,  1.91253236]],

       [[ 1.54527207,  1.1591055 ,  1.52892601,  1.82171419],
        [ 1.54527207,  1.1591055 ,  1.52892601,  1.82171419],
        [ 1.54527207,  1.1591055 ,  1.52892601,  1.82171419]],

       [[ 1.70086359,  1.45821037,  1.50392236,  1.91462561],
        [ 1.70086359,  1.45821037,  1.50392236,  1.91462561],
        [ 1.70086359,  1.45821037,  1.50392236,  1.91462561]]])

In [69]:
np.array_equal(x,y)

False

In [73]:
np.logical_or(x, y)

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]], dtype=bool)

In [77]:
my_array = np.arange(4)
my_array

array([0, 1, 2, 3])

In [78]:
print(my_array[1])

1


In [91]:
my_array2d = np.random.random((2,3))
my_array2d

array([[ 0.8662796 ,  0.84971322,  0.96812837],
       [ 0.20572323,  0.06906748,  0.97698904]])

In [92]:
print(my_array2d[1][2])

0.976989043638


In [94]:
print(my_array2d[1,2])

0.976989043638


In [99]:
my_array3d = np.random.random((3,5))
my_array3d

array([[ 0.15484537,  0.5786865 ,  0.67793351,  0.73926927,  0.67931313],
       [ 0.24454715,  0.60836722,  0.92929797,  0.16518556,  0.44621951],
       [ 0.93889053,  0.16874163,  0.79800688,  0.46668521,  0.14813655]])

In [120]:
my_array3d1 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12], [13,14,15,16]]])

In [121]:
my_array3d1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [125]:
print(my_array3d1[1,1,2])

15


In [124]:
# Select the element at the 1st index
print(my_array[1])

# Select the element at row 1 column 2
print(my_2d_array[1][2])

# Select the element at row 1 column 2
print(my_2d_array[1,2])

# Select the element at row 1, column 2 and 
print(my_3d_array[1,1,2])

1


NameError: name 'my_2d_array' is not defined